# Generated by Django 3.1.5 on 2021-02-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0009_carrucel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turismo.regiones')),
            ],
        ),
    ]
